bot:
  token: AAA
  chat_id: -1001349667662
modules:
  remove_joins: {}
  remove_leaves: {}
  remove_channel_messages: {}
  process_join_requests:
    question: "Привет! Для вступления в чат @ugractf расшифруй аббревиатуру CTF. Ответь мне тремя английскими словами."
    answer: "capture the flag"
    correct_feedback: "Отлично! Чат открыт: @ugractf. Общайся вежливо, не пиши анонимно и не предлагай людям биткоины."
    incorrect_feedback: "Увы, ответ неверный :( Попробуй ещё раз"
  logging:
    chat_id: 97631681
